### ISSUE TITLE
リポジトリ名を直感的にする

### ISSUE THREAD

**Issue by norihitoishida** [takucil/font-generate-for-uduki-2023#1]
@takucil リポジトリ作成ありがとうございます。早速ですが,`2023_uduki`という名前は抽象的でよく分からない+バッティングするので`font-generate-for-uduki-2023`等に変えて頂くことは可能でしょうか?

**Comment by takucil** [comment]
変更しました。リポジトリ名にはハイフンと小文字を使うのが一般的なんですね。githubの使い方を逐一ググってるレベルなので本当に助かります。ありがとうございます。
